spring.application.name=sistema-eventos
# Configuraci�n de la Conexi�n a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sweb_eclea_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuraci�n de JPA/Hibernate
# ddl-auto: 'create' para que hibernate cree las tablas al iniciar.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n de la aplicaci�n (JWT)
jwt.secret=41KAn5YGKWUrLRsQdqNVXGZQsbVKvW4gf1ELtwT2eD84BVqQNZG9J0LFFbcbAdED
# Duraci�n de la validez del token en milisegundos (86400000ms = 24 horas)
jwt.expiration.ms=86400000

# Google Gemini API Key
gemini.api.key=AIzaSyDypqauCPk_rU2sj6Z-QlZsVJMz2vilRVA